console.info('[Matterworks] Loading atmospheric processing recipes')

ServerEvents.recipes(event => {
    const compressedAir = 'kubejs:compressed_air'
    const nitrogen = 'chemlib:nitrogen_fluid'
    const oxygen = 'chemlib:oxygen_fluid'

    /*
     * ---------------------------------------------------------
     * Atmospheric capture / compression
     * ---------------------------------------------------------
     *
     * TEMPORARY 0.5.0 compatibility baseline.
     *
     * This recipe remains only until the 0.5.1 PneumaticCraft /
     * Compressed Creativity compatibility spike has passed runtime
     * validation. The intended replacement is real pneumatic pressure
     * generated by the Rotational Compressor, not Create compacting.
     */

    event.recipes.create.mixing(
        [
            Fluid.of(compressedAir, 1000),
            'create:filter'
        ],
        [
            'create:filter'
        ]
    )
        .id('matterworks:chemistry/atmosphere/capture_compressed_air')

    /*
     * ---------------------------------------------------------
     * Pressure-swing adsorption abstraction
     * ---------------------------------------------------------
     *
     * 1000 mB compressed air is separated approximately according to dry
     * atmospheric composition:
     *
     *   ~78 % nitrogen
     *   ~21 % oxygen
     *   ~ 1 % argon / trace gases (not recovered in this stage)
     *
     * Quartz currently represents a reusable silica-rich adsorption bed.
     * Matterworks Core will eventually replace this recipe abstraction with
     * pressure, bed saturation, cycle timing and purity constraints.
     */

    event.recipes.create.mixing(
        [
            Fluid.of(nitrogen, 780),
            Fluid.of(oxygen, 210),
            'minecraft:quartz'
        ],
        [
            Fluid.of(compressedAir, 1000),
            'minecraft:quartz'
        ]
    )
        .id('matterworks:chemistry/atmosphere/air_separation')

    console.info(
        '[Matterworks] Atmospheric processing registered: temporary 0.5.0 air path active pending pneumatic integration'
    )
})
