name = "Matterworks"
author = "F000NK"
version = "0.4.1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77f68b0a57cc8672a6d6e3c0185b8f0bf8e858b8bed56b38bed573cb0c0a3b8c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
