name = "Matterworks"
author = "F000NK"
version = "0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "417d951b7355ca73caf3e4a8a66a04a24bf7649ba2fe9ab54cdbfdc21c3055b3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
