name = "Matterworks"
author = "F000NK"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d82cab5bc087f29ee700ccc837c7183da634591086f2a429af17a0a226b44d64"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
